name: First Workflow
env:
  WORKFLOW_VAR: "This variable is decclared at the workflow level"

on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: Who to greet in the log
        required: true
        default: 'Maya the Mackerel'
        type: string

jobs:
  firstjob:
    #runs-on: self-hosted
    runs-on: Windows
    steps: 
      - name: firstjob script
        shell: cmd
        run: echo Hello World! This is the first job
        
  secondjob:
    #runs-on: ubuntu-latest
    env:
      JOB_VAR: "This is a job variable"
    runs-on: Linux
    needs: firstjob
    steps:
      - name: secondjob script
        shell: bash
        run: |
          echo This is the second 
          echo and this is a multi-line script
      - name: checkout
        uses: actions/checkout@v4
      - name: greetings
        id: print-to-log
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: ${{ inputs.who-to-greet }}
      - name: time
        run: |
          echo "The time of the greeting was at: ${{steps.print-to-log.outputs.time}}"
      - name: environment variables
        env:
          STEP_VAR: "This variable is declared at the step level"

  thirdjob:
      runs-on: ubuntu-latest
      needs: secondjob
      steps:
        - name: secondjob script
          shell: bash
          run: |
            echo This is the second 
            echo and this is a multi-line script
      
